version: "3.9"

services:
  duke-bank-db:
    image: postgres:16.1-bullseye
    container_name: "duke-bank-db"
    network_mode: "host"
    volumes:
      - ./src/main/resources/postgresql:/postgresql:ro
    environment:
      - POSTGRES_DB=rinhadb
      - POSTGRES_USER=duke
      - POSTGRES_PASSWORD=duke
    command: postgres -c shared_preload_libraries='pg_stat_statements'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s