GET http://localhost:8080/q/arc/beans

###
POST http://localhost:8080/clientes/1/transacoes
Content-Type: application/json

{
  "valor": 100000,
  "tipo": "c",
  "descricao": "#Credit TX"
}

###
POST http://localhost:8080/clientes/1/transacoes
Content-Type: application/json

{
  "valor": 100000,
  "tipo": "d",
  "descricao": "#Debit TX"
}